## On intel machine, ndk-build should just work out of the box
# build:
# 	ndk-build

# On M1 Macs, we have to use Ms.Rosetta to run android-ndk
build:
	arch -x86_64 /bin/bash -c ~/android-ndk-r21e/ndk-build